services:
  - docker:dind

variables:
  IMAGE_NAME: qdevelopment/q-client
  RELEASE_IMAGE_NAME: qblockchain/q-client
  BUILD_IMAGE: $IMAGE_NAME:$CI_COMMIT_SHA
  BUILD_DOCKERFILE: Dockerfile.alltools

.before_script_template:
  before_script:
    - git config --global url."https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/".insteadOf https://gitlab.com/
    - go env -w GOPRIVATE=gitlab.com/${CI_PROJECT_NAMESPACE}

stages:
  - build
  - test
  - release
  - deploy

.docker-login: &docker-login
  before_script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASS

test:
  image: golang:1.16.7
  stage: test
  extends: .before_script_template
  tags:
    - gitlab-org-docker
  only:
    - merge_requests
    - master
  script:
    - GO111MODULE=off go get gotest.tools/gotestsum
    - gotestsum --junitfile report.xml --format testname
  artifacts:
    when: always
    reports:
      junit: report.xml

lint:
  image: golang:1.16.7
  stage: test
  extends: .before_script_template
  tags:
    - gitlab-org-docker
  only:
    - merge_requests
    - master
  script:
    - go run build/ci.go lint

build:
  <<: [*docker-login]
  image: docker:latest
  stage: build
  tags:
    - gitlab-org-docker
  only:
    - master
    - latest
  script:
    - version=$(test -z $CI_COMMIT_TAG && echo $CI_COMMIT_SHA || echo $CI_COMMIT_TAG)
    - docker build --build-arg version="$version" --build-arg BUILD_TOKEN=${CI_JOB_TOKEN} --build-arg USERNAME=gitlab-ci-token -t $BUILD_IMAGE -f $BUILD_DOCKERFILE .
    - docker push $BUILD_IMAGE
    - docker tag $BUILD_IMAGE $IMAGE_NAME:latest
    - docker push $IMAGE_NAME:latest

build-mr:
  <<: [*docker-login]
  image: docker:latest
  stage: build
  tags:
    - gitlab-org-docker
  only:
    - merge_requests
  script:
    - version=$(test -z $CI_COMMIT_TAG && echo $CI_COMMIT_SHA || echo $CI_COMMIT_TAG)
    - docker build --build-arg version="$version" --build-arg BUILD_TOKEN=${CI_JOB_TOKEN} --build-arg USERNAME=gitlab-ci-token -t $BUILD_IMAGE -f $BUILD_DOCKERFILE .
    - docker push $BUILD_IMAGE
  interruptible: true

release:
  <<: [*docker-login]
  image: docker:latest
  stage: release
  tags:
    - gitlab-org-docker
  only:
    - tags
  script:
    - version=$(test -z $CI_COMMIT_TAG && echo $CI_COMMIT_SHA || echo $CI_COMMIT_TAG)
    - image=$RELEASE_IMAGE_NAME:$CI_COMMIT_TAG
    - docker build --build-arg version="$version" --build-arg BUILD_TOKEN=${CI_JOB_TOKEN} --build-arg USERNAME=gitlab-ci-token -t $BUILD_IMAGE -t $image -f $BUILD_DOCKERFILE .
    - docker push $BUILD_IMAGE
    - docker push $image
