services:
  - docker:dind

variables:
  IMAGE_NAME: registry.gitlab.com/q-dev/go-ethereum
  BUILD_IMAGE: $IMAGE_NAME:$CI_COMMIT_SHA
  BUILD_DOCKERFILE: Dockerfile

stages:
  - test
  - build

# build and publish docker image to the registry
build:
  image: docker:latest
  stage: build
  tags:
    - gitlab-org-docker
  only:
    - master
    - latest
    - /^v\d+\.\d+\.\d+$/ # semver tags
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    # build binary
    - version=$(test -z $CI_COMMIT_TAG && echo $CI_COMMIT_SHA || echo $CI_COMMIT_TAG)
    - docker build --build-arg version="$version" -t $BUILD_IMAGE -f $BUILD_DOCKERFILE .
    - docker push $BUILD_IMAGE

test:
  image: golang:1.14
  stage: test
  tags:
    - gitlab-org-docker
  only:
    - master
    - merge_requests
  script:
    - go test ./...