version: "3"

services:
  bootnode:
    image: {{ .Image }}
    container_name: bootnode
    entrypoint: ["bootnode", "-nodekey=/bootnode/boot.key", "-verbosity=9" , "-addr=172.25.0.100:30301"]
    volumes:
      - /opt/eth/bootnode:/bootnode
    networks:
      chainnet:
        ipv4_address: 172.25.0.100

  node-1:
    image: {{ .Image }}
    container_name: node-1
    depends_on:
      - bootnode
    ports:
      - 8000:8545
      - 30303:30303
    entrypoint: ["geth", "--datadir=/node1", "--networkid=128",  "--http", "--http.port=8545", "--http.addr=0.0.0.0", "--verbosity=9", "--nat=extip:172.25.0.101",  "--bootnodes=enode://85967845980e7bfb091d0fa373265a070f79e14785f3d3be4478490225c5ce53e6e5f1e348157fb09e03842499f6785f5e99dd408e2d4428a756b61775e89d11@172.25.0.100:30301", "--nousb"]
    volumes:
      - /opt/eth/node1:/node1
    networks:
      chainnet:
        ipv4_address: 172.25.0.101

  miner-1:
    image: {{ .Image }}
    container_name: miner-1
    depends_on:
      - bootnode
    ports:
      - 30304:30303
    entrypoint: ["geth", "--datadir=/data", "--unlock=36ce8a088e7ffacb0dbc6473fbd27f3844666ea0", "--password=/data/pwd.txt", "--nat=extip:172.25.0.102", "--mine", "--miner.threads=1", "--syncmode=full", "--networkid=128",  "--verbosity=3",  "--bootnodes=enode://85967845980e7bfb091d0fa373265a070f79e14785f3d3be4478490225c5ce53e6e5f1e348157fb09e03842499f6785f5e99dd408e2d4428a756b61775e89d11@172.25.0.100:30301", "--nousb"]
    volumes:
      - /opt/eth/miner1:/data
    networks:
      chainnet:
        ipv4_address: 172.25.0.102

  miner-2:
    image: {{ .Image }}
    container_name: miner-2
    depends_on:
      - bootnode
    ports:
      - 30305:30303
    entrypoint: ["geth", "--datadir=/data", "--unlock=c16ed238e9df13fdb4386acec0015d988b18cc12", "--password=/data/pwd.txt", "--nat=extip:172.25.0.103", "--mine", "--miner.threads=1", "--syncmode=full", "--networkid=128",  "--verbosity=3",  "--bootnodes=enode://a2c0a4f48c1a706f1150fce06e1c705c7bcbacc49d47b33eed62e30e7a75e36b9839224d69f3d4072dc91bd9e34b6b6547474dfd9b3431a8e8a0b5c4af3dd18d@172.25.0.100:30301", "--nousb"]
    volumes:
      - /opt/eth/miner2:/data
    networks:
      chainnet:
        ipv4_address: 172.25.0.103

networks:
  chainnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/24
